spring.datasource:
  hikari.maximum-pool-size: 4
  url:
  username:
  password:
  driver-class-name: org.postgresql.Driver

#spring:
#  jpa:
#    database: postgresql
#    hibernate:
#      dialect: org.hibernate.dialect.PostgreSQLDialect
#      ddl-auto: update
#    properties:
#      hibernate:
#        format_sql: true
#    show-sql: true
#  sql:
#    init:
#      platform: postgres

spring:
  datasource:
    url: jdbc:h2:mem:sns
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true


jwt:
  secret:
    key: 612E3DFC176A8E32A3E59C2AC65D2612E3DFC176A8E32A3E59C2AC65D2
  token:
    expired-time: 2592000000